### ISSUE TITLE
Merge the output and errors of the batch results

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#18]
@jservonnat could you merge the stdout and stderr streams when running a job, so that we have only one file to read when debugging?

I have quickly read `man qsub `on ciclad and I think the option you want (or I want) is '`-j join oe`'
```
       -j join Declares if the standard error stream of the job will be merged
               with the standard output stream of the job.

               An  option  argument  value  of oe directs that the two streams
               will be merged, intermixed,  as  standard  output.   An  option
               argument  value  of  eo  directs  that  the two streams will be
               merged, intermixed, as standard error.

               If the join argument is n or the option is not  specified,  the
               two streams will be two separate files.
```

I see there is such a directive at the beginning of job_C-ESM-EP.sh, but it will only work at TGCC
`#MSUB -eo`

**Comment by jservonnat** [comment]
Done. Thank you for the suggestion!

**Comment by jypeter** [comment]
@jservonnat I have just noticed that most job outputs have stdout and stderr nicely merged, except the `copy_html` jobs. Can you check where/how you launch these, and also merge the outputs?

### Example
```
[jypmce@ciclad-ng MainTimeSeries]$ pwd
/home/jypmce/C-ESM-EP/PMIP4_0k_ref/MainTimeSeries

[jypmce@ciclad-ng MainTimeSeries]$ ls -ltr *.e* *.o*
-rw-r--r-- 1 jypmce ipsl  17281 Nov 20 15:14 MainTimeSeries_PMIP4_0k_ref_C-ESM-EP.e638499
-rw-r--r-- 1 jypmce ipsl    344 Nov 20 15:14 copy_html_error_page.sh.o638500
-rw-r--r-- 1 jypmce ipsl      0 Nov 20 15:14 copy_html_error_page.sh.e638500

```

**Comment by jypeter** [comment]
@jservonnat can you re-open this issue (can't do it myself) till the copy_html_error_page.sh return jobs are merged (problem mentioned just above)

Also, the html page you get instead of an atlas when there is an error still says

`check the last .e and .o files in the directory of the component to see the error`

It should now be
`check the most recent '.eNNNN' and 'last.out' files in the directory of the component to get details about the error`

**Comment by jservonnat** [comment]
Done

**Comment by jservonnat** [comment]
whether you should look at the last.out or not is in the .eNNNN
